#! /usr/local/bin/ruby
# encoding: utf-8
ActiveRecord::Base.establish_connection
ActiveRecord::Base.connection.tables.each do |table|
  next if table == 'schema_migrations'
  # MySQL and PostgreSQL
  ActiveRecord::Base.connection.execute("TRUNCATE #{table}")
  # SQLite
  # ActiveRecord::Base.connection.execute("DELETE FROM #{table}")
end

Region.create(:name => "Đông Bắc Bộ", :code => "01")
Region.create(:name => "Tây Bắc Bộ", :code => "02")
Region.create(:name => "Đồng Bằng Sông Hồng", :code => "03")
Region.create(:name => "Bắc Trung Bộ", :code => "04")
Region.create(:name => "Nam Trung Bộ", :code => "05")
Region.create(:name => "Tây Nguyên", :code => "06")
Region.create(:name => "Đông Nam Bộ", :code => "07")
Region.create(:name => "Tây Nam Bộ", :code => "08")

Town.create(:name => "An Giang", :code => "01")
Town.create(:name => "Bà Rịa - Vũng Tàu", :code => "02")
Town.create(:name => "Bạc Liêu", :code => "03")
Town.create(:name => "Bắc Cạn", :code => "04")
Town.create(:name => "Bắc Giang", :code => "05")
Town.create(:name => "Bắc Ninh", :code => "06")
Town.create(:name => "Bến Tre", :code => "07")
Town.create(:name => "Bình Dương", :code => "08")
Town.create(:name => "Bình Định", :code => "09")
Town.create(:name => "Bình Phước", :code => "10")
Town.create(:name => "Bình Thuận", :code => "11")
Town.create(:name => "Cà Mau", :code => "12")
Town.create(:name => "Cao Bằng", :code => "13")
Town.create(:name => "Cần Thơ", :code => "14")
Town.create(:name => "Đà Nẵng", :code => "15")
Town.create(:name => "Đắk Lắk", :code => "16")
Town.create(:name => "Đắk Nông", :code => "17")
Town.create(:name => "Đồng Nai", :code => "18")
Town.create(:name => "Đồng Tháp", :code => "19")
Town.create(:name => "Điện Biên", :code => "20")
Town.create(:name => "Gia Lai", :code => "21")
Town.create(:name => "Hà Giang", :code => "22")
Town.create(:name => "Hà Nam", :code => "23")
Town.create(:name => "Hà Nội", :code => "24")
Town.create(:name => "Hà Tĩnh", :code => "25")
Town.create(:name => "Hải Dương", :code => "26")
Town.create(:name => "Hải Phòng", :code => "27")
Town.create(:name => "Hòa Bình", :code => "28")
Town.create(:name => "Hậu Giang", :code => "29")
Town.create(:name => "Hưng Yên", :code => "30")
Town.create(:name => "Tp.Hồ Chí Minh", :code => "31")
Town.create(:name => "Khánh Hòa", :code => "32")
Town.create(:name => "Kiên Giang", :code => "33")
Town.create(:name => "Kon Tum", :code => "34")
Town.create(:name => "Lai Châu", :code => "35")
Town.create(:name => "Lào Cai", :code => "36")
Town.create(:name => "Lạng Sơn", :code => "37")
Town.create(:name => "Lâm Đồng", :code => "38")
Town.create(:name => "Long An", :code => "39")
Town.create(:name => "Nam Định", :code => "40")
Town.create(:name => "Nghệ An", :code => "41")
Town.create(:name => "Ninh Bình", :code => "42")
Town.create(:name => "Ninh Thuận", :code => "43")
Town.create(:name => "Phú Thọ", :code => "44")
Town.create(:name => "Phú Yên", :code => "45")
Town.create(:name => "Quảng Bình", :code => "46")
Town.create(:name => "Quảng Nam", :code => "47")
Town.create(:name => "Quảng Ngãi", :code => "48")
Town.create(:name => "Quảng Ninh", :code => "49")
Town.create(:name => "Quảng Trị", :code => "50")
Town.create(:name => "Sóc Trăng", :code => "51")
Town.create(:name => "Sơn La", :code => "52")
Town.create(:name => "Tây Ninh", :code => "53")
Town.create(:name => "Thái Bình", :code => "54")
Town.create(:name => "Thái Nguyên", :code => "55")
Town.create(:name => "Thanh Hóa", :code => "56")
Town.create(:name => "Thừa Thiên - Huế", :code => "57")
Town.create(:name => "Tiền Giang", :code => "58")
Town.create(:name => "Trà Vinh", :code => "59")
Town.create(:name => "Tuyên Quang", :code => "60")
Town.create(:name => "Vĩnh Long", :code => "61")
Town.create(:name => "Vĩnh Phúc", :code => "62")
Town.create(:name => "Yên Bái", :code => "63")
